<?php

$MAX_ADC_VALUE = 65535;

$DATA_FILE_RAW = "smbus_A0.current";
$DATA_FILE_PPM = "smbus_A0.ppm";
$DATA_FILE_UGPM3 = "smbus_A0.ugpm3";

$DEFAULT_HISTORY_LENGTH = 180;
$POLLING_RATE = 1000;

$MAX_CHART_VALUE = 400;

?>
